name: sam2
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - torchaudio
  - pytorch-cuda=11.8
  - numpy
  - opencv
  - pandas
  - pillow
  - matplotlib
  - seaborn
  - scipy
  - tqdm
  - jupyter
  - ipykernel
  - pip
  - git
  
  # Additional dependencies for computer vision
  - scikit-image
  - imageio
  - ffmpeg
  - av
  
  # Development tools
  - black
  - flake8
  - pytest
  
  - pip:
    # SAM2 and related packages
    - git+https://github.com/facebookresearch/segment-anything-2.git
    - hydra-core
    - iopath
    - fairscale
    - timm
    - transformers
    - accelerate
    - xformers
    
    # Tracking dependencies
    - norfair>=2.2.0
    - filterpy>=1.4.5
    - rich>=13.0.0
    
    # Additional utilities
    - wandb
    - tensorboard
    - gradio
